version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/portfolio/src"
    open-pull-requests-limit: 6
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
      timezone: 'Europe/Berlin'
