version: '3.8'

services:
  
  sample:
    container_name: sample
    build:
      context: ./portfolio
      dockerfile: ../Dockerfile
      target: build
    # comment out volumes when target is prod and not build
    volumes:
      - './portfolio:/app'
    # comment out until here
    ports:
      - 3001:80
    networks:
      - portfolio
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: postgres:16.2
    environment:
    # using an .env file, but leaving defaults for easier first time run
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
    driver: bridge

volumes:
    postgres:
    pgadmin: