version: '3.8'

services:

  sample:
    container_name: sample
    build:
      context: ./portfolio
      dockerfile: ../Dockerfile
      target: prod
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3001:80
    networks:
      - portfolio
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - portfolio
    restart: unless-stopped

networks:
  portfolio:
    driver: bridge

volumes:
    postgres:
    pgadmin: