version: '3.8'

services:
  
  web:
    env_file:
      - .env
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    # comment out ports in prod, traffic only through proxy
    # ports:
    #   - ${NODE_PORT}:${NODE_PORT}
    networks:
      - portfolio
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database
  database:
    env_file:
      - .env
    image: postgres:16.2
    environment:
    # using an .env file, but leaving defaults for easier first time run
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
    volumes:
       - postgres:/data/postgres
    # comment out for prod, we don't need access
    ports:
      - "127.0.0.1:5433:${POSTGRES_PORT}"
    networks:
      - portfolio
    restart: unless-stopped
  server:
    # restart: always
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}
      - ${NGINX_PORT_HTTPS}:${NGINX_PORT_HTTPS}
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - web
    networks:
      - portfolio
networks:
  portfolio:
    driver: bridge

volumes:
    postgres:
    pgadmin: